### ISSUE TITLE
Erroneous notifications about lock state

### ISSUE THREAD

**Issue by PiotrMarzec** [ilcato/homebridge-fibaro-home-center#129]
I have a home automation system based on Fibaro Home Center 3 (locks, blinds, gates, door open/close sensors, lights). This setup works well, with no significant issues.

I've installed Homebridge on my Raspberry Pi, and added the Fibaro plugin and connected to my system. Everything went pretty smooth, all devices appeared in the Home app on my iPhone, and I can controll them.

BUT ;) a couple of times a day I will get a notification from the iOS Home app, "Front door lock was unlocked" and then usually a few moments later "Front door lock was locked". But there is no actuall change in the lock state, there are no automations running at the time, and no changes to the lock state.

In the Homebridge logs I can see:
[1/26/2023, 1:27:03 AM] [FibaroHC3] Updating value for device:  137  parameter: Lock Current State, value: false
[1/26/2023, 1:27:03 AM] [FibaroHC3] Updating value for device:  137  parameter: Lock Target State, value: false

In the Fibaro Home Center logs, there is no change in state.

**Comment by ilcato** [comment]
@PiotrMarzec are you able to call the `/api/refreshStates` function from home center ?
It's the endpoint I monitor in order to receive updates from Home Center.
Call it immediately after changing the lock state (in both directions) and return to me with the data.
I need to filter out the notifications that create the false positive in HomeKit.
Thanks
